name: pg-dump
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  db-backup:
    runs-on: ubuntu-latest
    steps:
      - name: show pg_dump version before update
        run: pg_dump -V
      - name: update
        run: |
          sudo apt-get remove postgresql-client-common
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install postgresql-client-15
          sudo systemctl stop postgresql
          sudo systemctl enable postgresql
          sudo systemctl start postgresql
      - name: show pg_dump version after update
        run: pg_dump -V
      - uses: actions/checkout@v2
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.5
        with:
          database_url: "postgres://postgres:hoduecaramelle@db.mmucqujjuxgcszwyrbil.supabase.co:5432/postgres"
          path: "backups/backup.sql" 
          options: "-O"